name: 'aspire'

channels:
  - defaults
  - conda-forge

dependencies:
  - click
  - cython=0.26.1
  - fftw
  - jupyter
  - make
  - matplotlib
  - numpy=1.14.2
  - numpydoc=0.7.0
  - pandas>=0.23.4
  - pillow
  - pip
  - pybind11
  - pytest
  - python=3.6
  - scikit-image=0.14.0
  - scikit-learn
  - scipy=1.3.0
  - wheel
  - pip:
    - console_progressbar
    - coveralls
    - finufftpy
    - importlib_resources>=1.0.2
    - mrcfile
    - pyfftw
    - pytest-cov
    - python-box
    - sphinxcontrib-bibtex
    - sphinx-rtd-theme==0.4.2
    - tqdm
    - numba
