name: 'aspire'

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python=3.9
  - numpy=1.25.0
  - scipy=1.13.1
  - scikit-learn
  - scikit-image
  - mkl=2024.1.*  # possible regression impacts eig solver in later versions up to 2025.0
